### ISSUE TITLE
[bug] Shield wires in cable nodes are rendered differently than spline shield wires

### ISSUE THREAD

**Issue by kvid** [formatc1702/WireViz#125]
[[Current dev branch](https://github.com/formatc1702/WireViz/tree/dev)]: As the spline shield wires are rendered as thin tinned wires with black borders, and the shield wires in cable nodes are rendered as a black single (bottom) border, they don't fit well together, e.g. in [tutorial03.png](https://github.com/formatc1702/WireViz/blob/dev/tutorial/tutorial03.png):
![tutorial03](https://user-images.githubusercontent.com/12657033/88470689-c11b5e00-ceff-11ea-8baf-960c8dfe413b.png)

**Comment by formatc1702** [comment]
true... personally I like displaying shields as thin black wires to match the line in the node, and to make them appear different from a black/grey regular wire. would that be better?

**Comment by kvid** [comment]
I will make a change in my PR #126 later today - probably in the evening.

**Comment by formatc1702** [comment]
FYI: In the multicolor wires PR, shields were represented as a thin _silver_ wire... My worry with that is that this offers poor contrast, especially when printing the diagram. While using colors is definitely helpful, I'm trying to make all the WireViz features work even when printed in B&W, and to keep it accessible to colorblind users (hence the explicit color names in the wire nodes)

**Comment by kvid** [comment]
@formatc1702 wrote:
> true... personally I like displaying shields as thin black wires to match the line in the node, and to make them appear different from a black/grey regular wire. would that be better?

I have now updated PR #126 according to your preference. In addition, it was very easy to also allow a colored shield as the current spline shield wires shown in the description above if the user wants that, by allowing to specify a color in `cable.shield`. See the comparison in the PR description, test it yourself, and let me know what you think.

**Comment by SnowMB** [comment]
> In the multicolor wires PR...

I just quickly hacked something because I was messing with the wire representation inside the cable table. It was not meant as a change suggestion. Sorry for the confusion. :sweat_smile:

**Comment by formatc1702** [comment]
@SnowMB don't worry, I was talking about the old PR #96. I know your work on stripes is WIP ;)
