### ISSUE TITLE
Apache License?

### ISSUE THREAD

**Issue by pdinc-oss** [formatc1702/WireViz#13]
I could get justification from work to contribute, but not on a GPL code base.

Thoughts?

**Comment by purpleidea** [comment]
@pdinc-oss Work somewhere else that isn't a hater, or help them get rid of their FUD.

**Comment by superlou** [comment]
While @purpleidea's recommendation may not be realistic, what are the cons of GPLv3 for an application like this?

**Comment by purpleidea** [comment]
The people who oppose copyleft are the ones it was designed to protect against.

> While @purpleidea's recommendation may not be realistic, what are the cons of GPLv3 for an application like this?

The con is that some company can't use this in their proprietary product.

**Comment by pdinc-oss** [comment]
> The people who oppose copyleft are the ones it was designed to protect against.
> 
> > While @purpleidea's recommendation may not be realistic, what are the cons of GPLv3 for an application like this?
> 
> The con is that some company can't use this in their proprietary product.

That is correct, and that is respected. Thank you for the response.
