### ISSUE TITLE
Using multiple color for wire makes ugly output 

### ISSUE THREAD

**Issue by X-Ryl669** [formatc1702/WireViz#131]
I'm using the dev branch as of today (last commit: b9a4783b6fba882234c3c3e2c74968dcfa38596d )
I'm using the example code as given in my comment in PR #120
I'm getting this output:
![image](https://user-images.githubusercontent.com/3277165/88508235-9522da00-cfde-11ea-9239-92d2ee3516ec.png)

I'd have expected that wires all have the same thickness, but they don't.

**Comment by formatc1702** [comment]
Currently, rendered wire thickness it is decided per cable/bundle: if any of the wires of a cable/bundle is multicolored, all the single-colored ones _in that group_ are rendered in the same thickness. This change was introduced in 8cba79334cb3bf689a9a3ace53fa2986bbe5abe7.

I agree that the output above does not look like a user would probably expect, so the check would have to happen on a harness level (is any wire _in the entire harness_ multicolored?).

I welcome a quick fix for this, but I will emphasize that wires should _still_ be rendered in the thin style if no multicolored wires appear in the harness, so as not to make them unnecessarily thick. In the future (see #120) this whole issue should disappear anyway, unless a user specifically needs lengthwise striped wires as opposed to rings.

**Comment by formatc1702** [comment]
I've made an adjustment in #132 that addresses the issue. IMHO, this does not look better than the picture posted above.

![test](https://user-images.githubusercontent.com/2447251/88520300-b0e4ab00-cff3-11ea-88d3-d4442509a181.png)

**Comment by X-Ryl669** [comment]
Yes I know, I've tried to play with it and got very frustrated too by this wavy rendering of graphviz. I prefer the version below than the one above.
