### ISSUE TITLE
[internal] Add linguist overrides

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#146]
Add some lines to `.gitattributes` to avoid WireViz being [labeled as a HTML project](https://github.com/formatc1702/WireViz/search?l=HTML) in the statistics.

![image](https://user-images.githubusercontent.com/2447251/89273488-e581e380-d63f-11ea-9ebd-3214fb40a24a.png)

[Reference](https://github.com/github/linguist#overrides)

**Comment by kvid** [comment]
Do you also at the same time consider adding `linguist-generated=true` entries for generated files as described in your link 2 in this https://github.com/formatc1702/WireViz/issues/100#issuecomment-660550710?

**Comment by kvid** [comment]
I believe #154 closed this issue.
