### ISSUE TITLE
[feature] Connector to Connector Mating

### ISSUE THREAD

**Issue by jtroeth1** [formatc1702/WireViz#148]
Hi,

Is there currently a way to mate two connectors together without a wire in between?
Eg a cable mount male connector mounting to a panel mount female connector.

In the attached image I would like to join X2 & X3 but X3 just loops onto itself.
![PT_Cable_Comb](https://user-images.githubusercontent.com/37925036/89590855-266e3800-d88c-11ea-9d4b-ccea6ce6419f.png)

**Comment by kvid** [comment]
> Is there currently a way to mate two connectors together without a wire in between?

Currently, this is not possible, but similar requests have been discussed. Your request seems to be related to (maybe a generalization of) #134 and a solution is also relevant to #142. See if the mockup in https://github.com/formatc1702/WireViz/issues/134#issuecomment-665877504 looks like something useful for you, with the dashed arrows between your X2 and X3?

**Comment by formatc1702** [comment]
Closing to consolidate with #134, will generalize title there to include this use case.
