### ISSUE TITLE
[feature]Images support

### ISSUE THREAD

**Issue by martonmiklos** [formatc1702/WireViz#159]
Hi @formatc1702 !

I have read here that you are planning to introduce support for images:
https://github.com/formatc1702/WireViz/blob/feature/syntax-description/docs/syntax.md

I am willing to contribute a PR if I get green light to implement what in that spec currently.

**Comment by formatc1702** [comment]
Hi, I'm on holiday right now but #153 implements this feature and is almost finished, so no need for a new PR at the moment. Thanks a lot, maybe you find another issue that interests you... make sure to check it's not being worked on already :)

**Comment by martonmiklos** [comment]
Ah my bad I was looking between the issues not the PRs.
