### ISSUE TITLE
[feature]Add ability to customize HTML output title

### ISSUE THREAD

**Issue by martonmiklos** [formatc1702/WireViz#182]
I think it would be beneficial to being able to provide a way to generate the title of the HTML output yaml. 
I often keep multiple windows/tabs containing Wirewiz generated outputs open and now I cannot distinguish easily between them:

![kép](https://user-images.githubusercontent.com/1609182/96504056-75edbe80-1254-11eb-963c-40389ab0dd8f.png)

Considered as a low hanging fruit to me in the case if noone has objections. I am also open for the syntax recommentations!

**Comment by kvid** [comment]
This has already been suggested in https://github.com/formatc1702/WireViz/issues/158#issuecomment-687924335. Feel free to join the syntax discussion in #158.

**Comment by formatc1702** [comment]
@martonmiklos if you feel that #158 is enough to address this topic (and the more general metadata question), please close this issue. If you feel it needs to remain open, please let me know why. No problem either way.

**Comment by martonmiklos** [comment]
Hi folks, my bad, but the github issue search did not resulted that issue by searching for 'title'.

Closing it, having it covered by the meta syntax is perfectly fine.
