### ISSUE TITLE
Custom Tables

### ISSUE THREAD

**Issue by ToniN9999** [formatc1702/WireViz#203]
I think it would be very beneficial if it would be possible to configure other custom tables similar to the BOM but to hold information such as drawing names, projects, authors, chnage information etc. Like below for example.

![image](https://user-images.githubusercontent.com/76157554/102473125-ff502000-404e-11eb-99bd-308299f1b6a8.png)

![image](https://user-images.githubusercontent.com/76157554/102473201-1a229480-404f-11eb-955f-e88724806ef6.png)

**Comment by formatc1702** [comment]
See #32, this is a WIP that pretty much covers what you want :)

**Comment by ToniN9999** [comment]
Thank you for that @formatc1702.
Apologies for not searching better i will close this request.
