### ISSUE TITLE
[Feature] Crimp ferrule direct to connector 

### ISSUE THREAD

**Issue by vtmatteo** [formatc1702/WireViz#204]
It would be great if we could show which crimp ferrule (part number) goes with which connector if it is a crimp+socket type of connector.

**Comment by kvid** [comment]
Have you tried cloning the dev branch? Please take a look at  [tutorial08.yml](https://github.com/tutorial08.yml/WireViz/blob/dev/tutorial/tutorial08.yml) and run it through WireWiz to see if that demonstrates what you request.

**Comment by kvid** [comment]
This fuctionality was merged into the `master` branch in 2021, so I assume we can safely close this issue. Please re-open it again @vtmatteo - if you disagree and feel your usecase is not yet fully supported.
