### ISSUE TITLE
[bug] Failing to assign the default cable length unit when not present

### ISSUE THREAD

**Issue by kvid** [formatc1702/WireViz#205]
The current `dev` has a bug that fails to assign the default cable length unit when not present. The cause is this line:
https://github.com/formatc1702/WireViz/blob/606ddbf9775da6300299640501083acfaef42077/src/wireviz/DataClasses.py#L231
The wrong attribute is tested. The correct code line should be:
```py
        elif self.length_unit is None:
```
I'm sorry that I approved #198 without detecting this bug. It was introduced in https://github.com/formatc1702/WireViz/pull/198/commits/694f3a3f96820eaf1faac9e9f1b769c6dbcb072f, and I suggested a modified version still containing the bug, that was applied in https://github.com/formatc1702/WireViz/pull/198/commits/d9b67e45677c2278eedeb7193b6895663140501f, but it was not detectable at run-time before removing the redundant code in https://github.com/formatc1702/WireViz/pull/198/commits/e9292fbf03434318c33b1bc0c5aba3c27c73af42.

This is a good example of a bug that would have been detected automatically by a proper regression testing protocol (see also #63), e.g. something like:
```bash
python build_examples.py
python build_examples.py -b dev-x2 compare
```
Note that `dev-x2` in the command above is a local branch where I have committed the generated files after merging in #70 with https://github.com/formatc1702/WireViz/commit/eebf932c8dba741c35f8e12a11ac52f0b5dd5d2a (the latest commit where the output was intentionally changed).

**Comment by formatc1702** [comment]
Thanks.

I hope we can somehow implement a more rigorous and automated regression testing / unit testing soon; unfortunately I can't guarantee I will have the time and energy to dive deeper into this topic. I'll add a comment to #63 and mark it as "help wanted".
