### ISSUE TITLE
[feature] set Background color in Connector and Wire Box

### ISSUE THREAD

**Issue by designer2k2** [formatc1702/WireViz#210]
Hello,
let me first thank you for WireViz, it helps me keeping the wires in my car sorted and documented.

With larger projects the output gets a bit difficult to grasp, as everything is white.

How about an option to set the background-color from either the entire box, or the topmost box?

An example:
![grafik](https://user-images.githubusercontent.com/1591573/104108534-c1e55800-52c5-11eb-9675-15c23661a9d4.png)

Manually edited in the svg:
![grafik](https://user-images.githubusercontent.com/1591573/104108558-ed684280-52c5-11eb-9340-08fef4809586.png)
If the entire box or the topmost im not shure, maybe the entire box can be a bit too much.

It would be nice if i can define this in the yml file, maybe as optional "bgcolor" that is passed to graphviz.

Anyway, thanks for WireViz!

**Comment by kvid** [comment]
@designer2k2 and others that might need this feature are invited to clone my branch in PR #219, test this feature, and then make a review or some other comment about the suggested implementation.

**Comment by designer2k2** [comment]
thanks kvid for #219, this solves my feature request 😀

I testes #219  and it works here for me as expected
