### ISSUE TITLE
[doc] Two different CONTRIBUTING.md documents present

### ISSUE THREAD

**Issue by kvid** [formatc1702/WireViz#216]
Two different `CONTRIBUTING.md` documents are present in the v0.2 release:
- https://github.com/formatc1702/WireViz/blob/master/CONTRIBUTING.md
- https://github.com/formatc1702/WireViz/blob/master/docs/CONTRIBUTING.md

This seems to have be caused by the release merging the `dev` branch (where this document was in the `docs` subfolder) into the `master` branch (where it was in the root folder). It is unfortunate that the most updated version is more difficult to find than the old version.

**Comment by formatc1702** [comment]
Fixed, thanks.
