### ISSUE TITLE
how to add image

### ISSUE THREAD

**Issue by picli3** [formatc1702/WireViz#281]
I have been trying to add an image of the connector, but I have not been successful nor do I see anything related in the tutorial.

![](https://i.imgur.com/VuXcCTu.png)

I'm putting it as HTML, I don't know.
![](https://i.imgur.com/9KQHINt.png)
I discovered this tool recently, and I find it very good.

**Comment by kvid** [comment]
Thank you for reporting this strange error message. I admit it doesn't tell you much about what really is the problem. We are discussing how to improve error messages in #207.

See [example-08](https://github.com/formatc1702/WireViz/tree/master/examples#example-08) and the [syntax doc](https://github.com/formatc1702/WireViz/blob/master/docs/syntax.md#images) for proper input syntax.

**Comment by picli3** [comment]
Thank you very much for answering, I'm doing it this way and it still doesn't work.
![](https://i.imgur.com/oBsMaSl.png)
i get the following error
![](https://i.imgur.com/u9QU9ol.png)

the image is in the same file path, use an absolute path and a relative path and the result is the same.

**Comment by kvid** [comment]
To be able to reproduce your use case, please provide your version numbers and full input YAML as described in the [guidelines](https://github.com/formatc1702/WireViz/blob/master/docs/CONTRIBUTING.md). The error might be triggered by something in your input YAML that is not shown in your excerpt above. Try also the original example-08 as input to see if that also triggers the same error. Both absolute and relative paths should work.

**Comment by picli3** [comment]
It already worked, I had a previous syntax problem.

thanks for your help.

<pre>
  X2:
    type: DT04-3P
    subtype: male
    pinlabels: [BAT+, BAT-, IGN]
    image:
      src: "/home/maykol/Documentos/cables/TPS/wifi.png"        # path to the image file
      # optional parameters:
      #caption: <str>     # text to display below the image
      #bgcolor: <color>   # Background color of entry in diagram component box
      width: 100      # Expand image cell to this minimum height
      #fixedsize: false # Avoid scaling to a fixed size
</pre>

![](https://i.imgur.com/ZwAU4Pb.png)

**Comment by kvid** [comment]
It seems this issue has been solved, and #292 might help to avoid similar mistakes in the future. Feel free to re-open this issue again @picli3 if you don't agree.
