### ISSUE TITLE
graphviz installation problem

### ISSUE THREAD

**Issue by rowlandcarson** [formatc1702/WireViz#36]
I am a complete newbie to Python. I installed Python on my Mac and configured it as advised by Matthew Broberg & Moshe Zadka at <https://opensource.com/article/19/5/python-3-default-mac>, including setting up HomeBrew.

I have tried to install graphviz using the command line:

brew install graphviz

but after quite a lot of action it stopped on an error with these lines:

==> Installing graphviz dependency: sqlite
==> ./configure --prefix=/usr/local/Cellar/sqlite/3.32.1 --enable-dynamic-extensions --enable-readline --disable-editline --enable-session
==> make install
Error: Directory not empty @ dir_s_rmdir - /usr/local/opt/sqlite

I recognise that the WireViz issues forum is probably not the right place to ask what I need to do to fix this, but perhaps some kind soul might be able to point me to the right place fro such a query.

Thanks in advance for any assistance offered.

in friendship

Rowland

**Comment by formatc1702** [comment]
I'm sorry I can't offer any assistance on this issue, since I can't reproduce the problem and lack experience with brew to give meaningful advice.

I will close the issue due to inactivity, and I hope you have found help elsewhere!
