### ISSUE TITLE
Demo 1 seems to contain wrong wiring

### ISSUE THREAD

**Issue by pmario** [formatc1702/WireViz#47]
Hi Folks, 

I just came to the repo to read the README. There was 1 thing, that immediately catched my Eye. Demo 1 seems to be a standard [serial connection](https://en.wikipedia.org/wiki/Serial_port) which IMO **should be**

RX (2) -- TX (3)
TX (3) -- RX (2)
GND (5) -- GND (1)

In your example it's

DCD -- RX 
RX -- TX
GND -- GND

which doesn't make sense at all. DCD is Data Carrier Detected and RX is Receive Data. I personally don't know a situation where this would make sense.

**Comment by formatc1702** [comment]
You are totally right. Fixed it (313346a01aab5eb1040539c91ecd38af9e70d941), and will be included in the next merge into master. Thanks!
