### ISSUE TITLE
[feature] Add support for line breaks

### ISSUE THREAD

**Issue by MikeCrookes** [formatc1702/WireViz#49]
Would be great to be able to add line breaks into the fields as long descriptions can extend the output past normal screen width

**Comment by formatc1702** [comment]
This sounds reasonable. Which fields in particular are you thinking of?
Surely the notes fields... any other? I wouldn't want the code to become too cluttered with too many `\n` to `<br>` conversions all over the place.

**Comment by MikeCrookes** [comment]
I'm not that familiar with all the fields (and what they do) but looking at the data classes I think may be useful for;
- name
- category
- type
- subtype
- notes (as you suggested)

**Comment by formatc1702** [comment]
I have started some work in the [`feature/linebreaks`](https://github.com/formatc1702/WireViz/tree/feature/linebreaks) branch.

I will add support for the following fields:
- `type`
- `subtype`
- `notes`

`name` is the unique designator for a component and should be short and sweet (e.g. `X1`), no need for line breaks.
`cagegory` is only used internally, currently to distinguish between connectors and ferrules, as well as between cables and wire bundles. Thus the user does not need to edit this field.

**Comment by formatc1702** [comment]
Closed by #64.
