### ISSUE TITLE
[feature] Manual BOM additions

### ISSUE THREAD

**Issue by MikeCrookes** [formatc1702/WireViz#51]
Nice feature would be to be able to manually (via the yml) add lines to the auto-generated BOM

**Comment by Tyler-Ward** [comment]
Commenting so issue can be assigned to me.

**Comment by Tyler-Ward** [comment]
A pull request for this has been opened in #80

A future expansion of this could be to add a list of extra parts for a connector or cable for example where a connector has a seperate backshell part or for things like spiral wrap, This would enable it to be templated as part of the connector or cable and for qty and designators to be calculated automaticaly.

**Comment by formatc1702** [comment]
Closed. Feel free to open a new issue for adding custom BOM items within a connector! Sounds like a useful feature.
What about within a cable? Any situation where that might be useful?

**Comment by aakatz3** [comment]
Could be useful to have custom bom within a cable (or maybe a bundle?) for example, heat shrink, or sleeving
