### ISSUE TITLE
[feature] color mark at connector pins

### ISSUE THREAD

**Issue by quotschmacher** [formatc1702/WireViz#53]
add the ability to add a small color mark or something similar at connector pins.

**Comment by formatc1702** [comment]
You mean each pin might have a color assigned to it? That would mean we would need a new optional list-type parameter with the same length as pinout (and optionally pinnumbers). This sounds like a good idea.

I was also thinking of the option to specify a color for the entire connector (just in case).

If anybody wants to take this on, please let me know. I don't think I will find time for this soon, myself.

Thanks for the request!

**Comment by formatc1702** [comment]
Internal note: This (both the original suggestion and the ability to assign color to entire connector) will require rewriting the node's GraphViz code from a `record` (which is much more compact code-wise, but does not support colors inside cells AFAIK) to a proper HTML node (just like cables are already implemented)

**Comment by formatc1702** [comment]
Update: Ferrules have been refactored in #65. Original issue still open.

**Comment by formatc1702** [comment]
> Internal note: This (both the original suggestion and the ability to assign color to entire connector) will require rewriting the node's GraphViz code from a `record` (which is much more compact code-wise, but does not support colors inside cells AFAIK) to a proper HTML node (just like cables are already implemented)

Update: Ferrules have been refactored in #65. Original issue still open.
