### ISSUE TITLE
Ability to add internal part numbers and special instructions

### ISSUE THREAD

**Issue by sahil48** [formatc1702/WireViz#6]
It would be great to be able to add our internal part numbers for different wires and connectors and notes with special instructions (ex. how much to wind the wires, how much insulation to cut, warnings, etc.

**Comment by kvid** [comment]
You can already put special instructions in the connector and cable `notes` attribute. See how in the https://github.com/formatc1702/WireViz/tree/master/tutorial number 4, and if https://github.com/formatc1702/WireViz/pull/28 is accepted, then you can put internal part numbers as leading or trailing part of the connector and cable `type` attribute. Would these two attributes solve your issue?

**Comment by formatc1702** [comment]
Discussion about part numbers is already happening in #11, other instructions can be placed in the `notes` section as @kvid has mentioned.
