### ISSUE TITLE
[internal] Refactor HTML generation for GraphViz output

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#66]
#65 introduced [a more elegant way](https://github.com/formatc1702/WireViz/pull/65/files#diff-f3f7c9cc77f143d3a653259c03d87d40R63-R82) to generate the HTML code to use inside the GraphViz nodes.

So far, it's only implemented for ferrules. I will implement similar changes for [non ferrule] connectors as well as for cables/wire bundles, as soon as #17 is merged (to avoid any further trouble while merging.

**Comment by formatc1702** [comment]
Work for connectors has started in the [`feature/gv-html-refactor`](https://github.com/formatc1702/WireViz/tree/feature/gv-html-refactor) branch.

**Comment by aakatz3** [comment]
Should likely be implemented with part of #123 (noted in discussion)

**Comment by formatc1702** [comment]
See my comment there.

> In order not to further complicate things, I'd like to move the HTML output as-is to this new module... the HTML itself is a story for another day (#74).
