### ISSUE TITLE
[bug] Inconsistent horizontal alignment

### ISSUE THREAD

**Issue by kvid** [formatc1702/WireViz#90]
Single-line connector attributes are centered horizontally in the diagram when smaller than the available space, but the `graphviz_line_breaks()` function makes multi-line attributes left aligned:
https://github.com/formatc1702/WireViz/blob/34cd9c26126231eeb25f93af245b0a24e8d45ed8/src/wireviz/wv_helper.py#L120

In the wire nodes (formatted with HTML), both single- and multi-line attributes are centered.

**Comment by kvid** [comment]
Some users might argue that they prefer left-aligned multi-line attributes. IMHO, that would be a new feature request.

**Comment by formatc1702** [comment]
I intentionally used `\l` because I thought it would look better, but you are right, centered looks more consistent. I'll think about adding alignment options later, but it's not a priority.
